### ISSUE TITLE
buffer: mailgun panic

### ISSUE THREAD

**Issue by onestraw** [vulcand/oxy#147]
```go
panic: runtime error: slice bounds out of range

goroutine 277423 [running]:
io.(*multiReader).Read(0xc420a12320, 0xc421408000, 0x2000, 0x2000, 0x46bcb2, 0x1, 0x5313eb)
	/opt/go/src/io/multi.go:31 +0x2da
xxxxxxxx/vendor/github.com/mailgun/multibuf.(*multiReaderSeek).Read(0xc4203d7ec0, 0xc421408000, 0x2000, 0x2000, 0xc4299fe0a0, 0xc420c9b810, 0xc420612b58)
	/opt/build/src/xxxxxxxx/vendor/github.com/mailgun/multibuf/buffer.go:229 +0x52
io/ioutil.(*nopCloser).Read(0xc420f370a0, 0xc421408000, 0x2000, 0x2000, 0x0, 0xc420612ba0, 0x514107)
	<autogenerated>:1 +0x6b
io/ioutil.devNull.ReadFrom(0x0, 0x7fa9d1f15c68, 0xc420f370a0, 0x8d02c0, 0xc76201, 0x7fa9d1f15d08)
	/opt/go/src/io/ioutil/ioutil.go:144 +0x85
io/ioutil.(*devNull).ReadFrom(0xccf440, 0x7fa9d1f15c68, 0xc420f370a0, 0x7fa9d1f15d08, 0xccf440, 0x1)
	<autogenerated>:6 +0x61
io.copyBuffer(0xc782e0, 0xccf440, 0x7fa9d1f15c68, 0xc420f370a0, 0x0, 0x0, 0x0, 0x1d8, 0x0, 0x0)
	/opt/go/src/io/io.go:384 +0x2cb
io.Copy(0xc782e0, 0xccf440, 0x7fa9d1f15c68, 0xc420f370a0, 0x1d8, 0x0, 0x0)
	/opt/go/src/io/io.go:360 +0x68
net/http.(*transferWriter).WriteBody(0xc4202e5f00, 0xc75e20, 0xc420381900, 0x2, 0x2)
	/opt/go/src/net/http/transfer.go:324 +0x6c4
net/http.(*Request).write(0xc4211ccd00, 0xc75e20, 0xc420381900, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/request.go:622 +0x6e9
net/http.(*persistConn).writeLoop(0xc420788fc0)
	/opt/go/src/net/http/transport.go:1707 +0x1ad
created by net/http.(*Transport).dialConn
	/opt/go/src/net/http/transport.go:1118 +0xa5a
```

**Comment by Juliens** [comment]
I don't see anything about oxy in the stack trace. Could you give us some context on this panic?

**Comment by onestraw** [comment]
@ldez As I didn't find the root cause, it looks like randomly generated.
I will try to reproduce, but could you review/audit the `multibuf` related code at the same time?

**Comment by onestraw** [comment]
bash$ more /usr/local/go/src/io/multi.go
```golang
// Copyright 2010 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package io

type eofReader struct{}

func (eofReader) Read([]byte) (int, error) {
        return 0, EOF
}

type multiReader struct {
        readers []Reader
}

func (mr *multiReader) Read(p []byte) (n int, err error) {
        for len(mr.readers) > 0 {
                // Optimization to flatten nested multiReaders (Issue 13558).
                if len(mr.readers) == 1 {
                        if r, ok := mr.readers[0].(*multiReader); ok {
                                mr.readers = r.readers
                                continue
                        }
                }
                n, err = mr.readers[0].Read(p)
                if err == EOF {
                        // Use eofReader instead of nil to avoid nil panic
                        // after performing flatten (Issue 18232).
                        mr.readers[0] = eofReader{} // permit earlier GC
line 31:                        mr.readers = mr.readers[1:]
                }
                if n > 0 || err != EOF {
                        if err == EOF && len(mr.readers) > 0 {
                                // Don't return EOF yet. More readers remain.
                                err = nil
                        }
                        return
                }
        }
        return 0, EOF
}
```
As the panic shows, the length of mr.readers in line 31 is 0, otherwise it won't panic, but `len(mr.readers) >0 ` always true at here, it’s self-contradictory.
